/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konek;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samsul
 */
public class frame2 extends javax.swing.JFrame {
    public static Connection con;
    public static Statement stat;
    public static ResultSet res;
    /**
     * Creates new form tb_fifa
     */
    public frame2() {
        initComponents();
        konekmysql();
        frame2();
    }
    
        public void konekmysql(){
        try {
            String url= "jdbc:mysql://localhost:3306/fifa";
            String user= "root";
            String pass= "";
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url,user,pass);
            stat=con.createStatement();
            JOptionPane.showMessageDialog(null, "Data Berhasil DI Tampilkan");
                         
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagala Ditampilkan" + e.getMessage());
        }
    }
    public void frame2(){
        DefaultTableModel tb = new DefaultTableModel();
        //judul kolom
        tb.addColumn("ID");
        tb.addColumn("id_pemain");
        tb.addColumn("name");
        tb.addColumn("club");
        tb.addColumn("age");
        tb.addColumn("jersy_number");
        tb.addColumn("negara");
        tb.addColumn("joined");
        tb.addColumn("Loaned_From");
        tb.addColumn("Contract_Valid_Until");
        tb.addColumn("reputasi_international");
        tb.addColumn("potensi");
        tb.addColumn("posisi");
        tb.addColumn("Release Clause");
        tb.addColumn("nilai");
        tb.addColumn("wage");
        jTable1.setModel(tb);
        
        try{
        //ambil database
        res=stat.executeQuery("SELECT * FROM tabel_1 INNER JOIN tabel_2 on tabel_1.id_pemain = tabel_2.id_pemain ORDER BY nilai,wage");
        while (res.next()){
            //record database
            tb.addRow(new Object[]{
            res.getString("ID"),
            res.getString("id_pemain"),
            res.getString("name"),
            res.getString("club"),
            res.getString("age"),
            res.getString("jersy_number"),
            res.getString("negara"),
            res.getString("joined"),
            res.getString("Loaned_From"),
            res.getString("Contract_valid_Until"),
            res.getString("reputasi_international"),
            res.getString("potensi"),
            res.getString("posisi"),
            res.getString("Release Clause"),
            res.getString("nilai"),
            res.getString("wage"),
            
            
            
            
            });
            
        }
            
        }catch(SQLException e){
        System.out.println("koneksi berhasil" + e.getMessage());
     }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
